name: Build Release Image

on:
  push:
    branches:
      - 'main'

jobs:
  build-image:
    name: build image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Fast local build (amd64 only) for the healthcheck
      - name: Build (amd64, load locally)
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: |
            gaoxiangfei/anki-sync-server:25.09.2
            gaoxiangfei/anki-sync-server:latest
          build-args: |
            NOW=${{ github.event.pull_request.updated_at }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Wait for healthchecks
        run: docker run -e SYNC_USER1=test_user_name:test_user_password -d gaoxiangfei/anki-sync-server:latest | timeout 60s sh -c 'until docker ps | grep gaoxiangfei/anki-sync-server:latest | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gaoxiangfei/anki-sync-server:25.09.2
            gaoxiangfei/anki-sync-server:latest
          build-args: |
            NOW=${{ github.event.pull_request.updated_at }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
